#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QL_linhKienDienThoai")]
public partial class connectSQLDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  #endregion
	
	public connectSQLDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QL_linhKienDienThoaiConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public connectSQLDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public connectSQLDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public connectSQLDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public connectSQLDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<CucSacDuPhong> CucSacDuPhongs
	{
		get
		{
			return this.GetTable<CucSacDuPhong>();
		}
	}
	
	public System.Data.Linq.Table<DangNhap> DangNhaps
	{
		get
		{
			return this.GetTable<DangNhap>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_DangNhap")]
	public ISingleResult<Sp_DangNhapResult> Sp_DangNhap([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TaiKhoan", DbType="NChar(50)")] string taiKhoan, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MatKhau", DbType="NChar(20)")] string matKhau)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), taiKhoan, matKhau);
		return ((ISingleResult<Sp_DangNhapResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_dongia")]
	public ISingleResult<sp_dongiaResult> sp_dongia()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<sp_dongiaResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_TimKiemOpLung")]
	public ISingleResult<sp_TimKiemOpLungResult> sp_TimKiemOpLung([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(128)")] string ten)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ten);
		return ((ISingleResult<sp_TimKiemOpLungResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_TimKiemCuSac")]
	public ISingleResult<sp_TimKiemCuSacResult> sp_TimKiemCuSac([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(128)")] string ten)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ten);
		return ((ISingleResult<sp_TimKiemCuSacResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_TimKiem")]
	public ISingleResult<sp_TimKiemResult> sp_TimKiem([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(128)")] string ten)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ten);
		return ((ISingleResult<sp_TimKiemResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_HienThiChiTietSP")]
	public ISingleResult<sp_HienThiChiTietSPResult> sp_HienThiChiTietSP([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaSP", DbType="NChar(10)")] string maSP)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maSP);
		return ((ISingleResult<sp_HienThiChiTietSPResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_HienThiChiTietCucSac")]
	public ISingleResult<sp_HienThiChiTietCucSacResult> sp_HienThiChiTietCucSac([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaSP", DbType="NChar(10)")] string maSP)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maSP);
		return ((ISingleResult<sp_HienThiChiTietCucSacResult>)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CucSacDuPhong")]
public partial class CucSacDuPhong
{
	
	private string _MaCucSac;
	
	private string _TenCucSac;
	
	private decimal _DonGia;
	
	private string _HinhMinhHoa;
	
	private string _MoTa;
	
	public CucSacDuPhong()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCucSac", DbType="NChar(20) NOT NULL", CanBeNull=false)]
	public string MaCucSac
	{
		get
		{
			return this._MaCucSac;
		}
		set
		{
			if ((this._MaCucSac != value))
			{
				this._MaCucSac = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCucSac", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
	public string TenCucSac
	{
		get
		{
			return this._TenCucSac;
		}
		set
		{
			if ((this._TenCucSac != value))
			{
				this._TenCucSac = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Money NOT NULL")]
	public decimal DonGia
	{
		get
		{
			return this._DonGia;
		}
		set
		{
			if ((this._DonGia != value))
			{
				this._DonGia = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhMinhHoa", DbType="NChar(50)")]
	public string HinhMinhHoa
	{
		get
		{
			return this._HinhMinhHoa;
		}
		set
		{
			if ((this._HinhMinhHoa != value))
			{
				this._HinhMinhHoa = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string MoTa
	{
		get
		{
			return this._MoTa;
		}
		set
		{
			if ((this._MoTa != value))
			{
				this._MoTa = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DangNhap")]
public partial class DangNhap
{
	
	private string _TaiKhoan;
	
	private string _MatKhau;
	
	public DangNhap()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="NChar(50)")]
	public string TaiKhoan
	{
		get
		{
			return this._TaiKhoan;
		}
		set
		{
			if ((this._TaiKhoan != value))
			{
				this._TaiKhoan = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NChar(20)")]
	public string MatKhau
	{
		get
		{
			return this._MatKhau;
		}
		set
		{
			if ((this._MatKhau != value))
			{
				this._MatKhau = value;
			}
		}
	}
}

public partial class Sp_DangNhapResult
{
	
	private System.Nullable<int> _KetQua;
	
	public Sp_DangNhapResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KetQua", DbType="Int")]
	public System.Nullable<int> KetQua
	{
		get
		{
			return this._KetQua;
		}
		set
		{
			if ((this._KetQua != value))
			{
				this._KetQua = value;
			}
		}
	}
}

public partial class sp_dongiaResult
{
	
	private string _HinhMinhHoa;
	
	private string _Ten;
	
	private System.Nullable<decimal> _DonGia;
	
	private string _Hang;
	
	public sp_dongiaResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhMinhHoa", DbType="NChar(100)")]
	public string HinhMinhHoa
	{
		get
		{
			return this._HinhMinhHoa;
		}
		set
		{
			if ((this._HinhMinhHoa != value))
			{
				this._HinhMinhHoa = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(128)")]
	public string Ten
	{
		get
		{
			return this._Ten;
		}
		set
		{
			if ((this._Ten != value))
			{
				this._Ten = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Money")]
	public System.Nullable<decimal> DonGia
	{
		get
		{
			return this._DonGia;
		}
		set
		{
			if ((this._DonGia != value))
			{
				this._DonGia = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hang", DbType="NVarChar(50)")]
	public string Hang
	{
		get
		{
			return this._Hang;
		}
		set
		{
			if ((this._Hang != value))
			{
				this._Hang = value;
			}
		}
	}
}

public partial class sp_TimKiemOpLungResult
{
	
	private string _MaOpLung;
	
	private string _Ten;
	
	private System.Nullable<decimal> _DonGia;
	
	private string _HinhMinhHoa;
	
	private string _MoTa;
	
	private string _Hang;
	
	public sp_TimKiemOpLungResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaOpLung", DbType="NChar(10)")]
	public string MaOpLung
	{
		get
		{
			return this._MaOpLung;
		}
		set
		{
			if ((this._MaOpLung != value))
			{
				this._MaOpLung = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(128)")]
	public string Ten
	{
		get
		{
			return this._Ten;
		}
		set
		{
			if ((this._Ten != value))
			{
				this._Ten = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Money")]
	public System.Nullable<decimal> DonGia
	{
		get
		{
			return this._DonGia;
		}
		set
		{
			if ((this._DonGia != value))
			{
				this._DonGia = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhMinhHoa", DbType="NChar(100)")]
	public string HinhMinhHoa
	{
		get
		{
			return this._HinhMinhHoa;
		}
		set
		{
			if ((this._HinhMinhHoa != value))
			{
				this._HinhMinhHoa = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string MoTa
	{
		get
		{
			return this._MoTa;
		}
		set
		{
			if ((this._MoTa != value))
			{
				this._MoTa = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hang", DbType="NVarChar(50)")]
	public string Hang
	{
		get
		{
			return this._Hang;
		}
		set
		{
			if ((this._Hang != value))
			{
				this._Hang = value;
			}
		}
	}
}

public partial class sp_TimKiemCuSacResult
{
	
	private string _MaCucSac;
	
	private string _TenCucSac;
	
	private decimal _DonGia;
	
	private string _HinhMinhHoa;
	
	private string _MoTa;
	
	private string _Hang;
	
	public sp_TimKiemCuSacResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCucSac", DbType="NChar(10) NOT NULL", CanBeNull=false)]
	public string MaCucSac
	{
		get
		{
			return this._MaCucSac;
		}
		set
		{
			if ((this._MaCucSac != value))
			{
				this._MaCucSac = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCucSac", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
	public string TenCucSac
	{
		get
		{
			return this._TenCucSac;
		}
		set
		{
			if ((this._TenCucSac != value))
			{
				this._TenCucSac = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Money NOT NULL")]
	public decimal DonGia
	{
		get
		{
			return this._DonGia;
		}
		set
		{
			if ((this._DonGia != value))
			{
				this._DonGia = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhMinhHoa", DbType="NChar(50)")]
	public string HinhMinhHoa
	{
		get
		{
			return this._HinhMinhHoa;
		}
		set
		{
			if ((this._HinhMinhHoa != value))
			{
				this._HinhMinhHoa = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string MoTa
	{
		get
		{
			return this._MoTa;
		}
		set
		{
			if ((this._MoTa != value))
			{
				this._MoTa = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hang", DbType="NVarChar(50)")]
	public string Hang
	{
		get
		{
			return this._Hang;
		}
		set
		{
			if ((this._Hang != value))
			{
				this._Hang = value;
			}
		}
	}
}

public partial class sp_TimKiemResult
{
	
	private string _MaTaiNghe;
	
	private string _Ten;
	
	private string _Hang;
	
	private string _Mota;
	
	private string _HinhMinhHoa;
	
	private System.Nullable<decimal> _DonGia;
	
	public sp_TimKiemResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTaiNghe", DbType="NChar(10) NOT NULL", CanBeNull=false)]
	public string MaTaiNghe
	{
		get
		{
			return this._MaTaiNghe;
		}
		set
		{
			if ((this._MaTaiNghe != value))
			{
				this._MaTaiNghe = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(128)")]
	public string Ten
	{
		get
		{
			return this._Ten;
		}
		set
		{
			if ((this._Ten != value))
			{
				this._Ten = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hang", DbType="NVarChar(50)")]
	public string Hang
	{
		get
		{
			return this._Hang;
		}
		set
		{
			if ((this._Hang != value))
			{
				this._Hang = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mota", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string Mota
	{
		get
		{
			return this._Mota;
		}
		set
		{
			if ((this._Mota != value))
			{
				this._Mota = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhMinhHoa", DbType="NChar(100)")]
	public string HinhMinhHoa
	{
		get
		{
			return this._HinhMinhHoa;
		}
		set
		{
			if ((this._HinhMinhHoa != value))
			{
				this._HinhMinhHoa = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Money")]
	public System.Nullable<decimal> DonGia
	{
		get
		{
			return this._DonGia;
		}
		set
		{
			if ((this._DonGia != value))
			{
				this._DonGia = value;
			}
		}
	}
}

public partial class sp_HienThiChiTietSPResult
{
	
	private string _MaTaiNghe;
	
	private string _Ten;
	
	private string _Hang;
	
	private string _Mota;
	
	private string _HinhMinhHoa;
	
	private System.Nullable<decimal> _DonGia;
	
	public sp_HienThiChiTietSPResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTaiNghe", DbType="NChar(10) NOT NULL", CanBeNull=false)]
	public string MaTaiNghe
	{
		get
		{
			return this._MaTaiNghe;
		}
		set
		{
			if ((this._MaTaiNghe != value))
			{
				this._MaTaiNghe = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(128)")]
	public string Ten
	{
		get
		{
			return this._Ten;
		}
		set
		{
			if ((this._Ten != value))
			{
				this._Ten = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hang", DbType="NVarChar(50)")]
	public string Hang
	{
		get
		{
			return this._Hang;
		}
		set
		{
			if ((this._Hang != value))
			{
				this._Hang = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mota", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string Mota
	{
		get
		{
			return this._Mota;
		}
		set
		{
			if ((this._Mota != value))
			{
				this._Mota = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhMinhHoa", DbType="NChar(100)")]
	public string HinhMinhHoa
	{
		get
		{
			return this._HinhMinhHoa;
		}
		set
		{
			if ((this._HinhMinhHoa != value))
			{
				this._HinhMinhHoa = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Money")]
	public System.Nullable<decimal> DonGia
	{
		get
		{
			return this._DonGia;
		}
		set
		{
			if ((this._DonGia != value))
			{
				this._DonGia = value;
			}
		}
	}
}

public partial class sp_HienThiChiTietCucSacResult
{
	
	private string _Ten;
	
	private System.Nullable<decimal> _DonGia;
	
	private string _HinhMinhHoa;
	
	private string _MoTa;
	
	public sp_HienThiChiTietCucSacResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(128)")]
	public string Ten
	{
		get
		{
			return this._Ten;
		}
		set
		{
			if ((this._Ten != value))
			{
				this._Ten = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Money")]
	public System.Nullable<decimal> DonGia
	{
		get
		{
			return this._DonGia;
		}
		set
		{
			if ((this._DonGia != value))
			{
				this._DonGia = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhMinhHoa", DbType="NChar(100)")]
	public string HinhMinhHoa
	{
		get
		{
			return this._HinhMinhHoa;
		}
		set
		{
			if ((this._HinhMinhHoa != value))
			{
				this._HinhMinhHoa = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string MoTa
	{
		get
		{
			return this._MoTa;
		}
		set
		{
			if ((this._MoTa != value))
			{
				this._MoTa = value;
			}
		}
	}
}
#pragma warning restore 1591
